name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run tests
        run: .github/test.sh
